<a href="https://colab.research.google.com/github/Spofted/WIA1007_-TUTORIAL_03/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np;

arr_2b2 = np.array([[2,3],[8,5]]);
print(arr_2b2);

print("\n");

arr_3b4 = np.array([[2,4,6,8],[1,3,5,7],[9,8,7,6]]);
print(arr_3b4);

print("\n");

arr_1 = np.ones((2,2));
print(arr_1);

print("\n");

arr_0 = np.zeros((2,2));
print(arr_0);

print("\n");

arr_6b3 = np.array([[1,2,3],[2,4,6],[3,6,9],[4,8,12],[5,10,15],[6,12,18]]);
print("6 by 3 array :\n", arr_6b3);
print("\n");
tarr_6b3 = np.transpose(arr_6b3);
print("Tranposed 6 by 3 array :\n", tarr_6b3);

print("\n");

a = np.array([[2,4],[3,6]]);
b = np.array([[3,6,9],[4,8,12]]);
product = np.dot(a,b);
print("Dot product of 2x2 and 2x3 :\n", product);

[[2 3]
 [8 5]]


[[2 4 6 8]
 [1 3 5 7]
 [9 8 7 6]]


[[1. 1.]
 [1. 1.]]


[[0. 0.]
 [0. 0.]]


6 by 3 array :
 [[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


Tranposed 6 by 3 array :
 [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]


Dot product of 2x2 and 2x3 :
 [[22 44 66]
 [33 66 99]]
